// Shared by the options page and the fill script. Safe to inject more than once.
(function () {
  if (window.RM_FIELDS) return;
  const DECLINE = "I don't wish to answer";

  // What you fill in on the settings page. [key, label, default, group, hint]
  const PROFILE = [
    ['first_name', 'First name', '', 'You'],
    ['last_name', 'Last name', '', 'You'],
    ['preferred_name', 'Preferred name', '', 'You', 'Leave blank to use your first name'],
    ['pronouns', 'Pronouns', '', 'You'],
    ['email', 'Email', '', 'You'],
    ['phone', 'Phone', '', 'You', 'Digits only works best, e.g. 5195551234'],
    ['phone_country', 'Phone country code', '+1', 'You'],
    ['address', 'Street address', '', 'Address'],
    ['city', 'City', '', 'Address'],
    ['province_state', 'Province or state', '', 'Address', 'Full name works best on dropdowns, e.g. Ontario'],
    ['postal', 'Postal or ZIP code', '', 'Address'],
    ['country', 'Country', 'Canada', 'Address'],
    ['linkedin', 'LinkedIn URL', '', 'Links'],
    ['github', 'GitHub URL', '', 'Links'],
    ['website', 'Website or portfolio', '', 'Links'],
    ['school', 'School', '', 'School'],
    ['degree', 'Degree', "Bachelor's", 'School', "e.g. Bachelor's, Bachelor of Applied Science"],
    ['major', 'Major / program', '', 'School'],
    ['gpa', 'GPA', '', 'School', 'Leave blank to skip GPA questions'],
    ['grad_month', 'Graduation month', 'May', 'School'],
    ['grad_year', 'Graduation year', '', 'School'],
    ['start_available', 'Earliest start date', '', 'School', 'e.g. May 2027'],
    ['work_auth_us', 'Allowed to work in the US?', 'No', 'Work eligibility'],
    ['need_sponsor_us', 'Need visa sponsorship for the US?', 'Yes', 'Work eligibility'],
    ['work_auth_ca', 'Allowed to work in Canada?', 'Yes', 'Work eligibility'],
    ['need_sponsor_ca', 'Need sponsorship for Canada?', 'No', 'Work eligibility'],
    ['relocate', 'Willing to relocate?', 'Yes', 'Work eligibility'],
    ['over_18', 'At least 18?', 'Yes', 'Work eligibility'],
    ['how_heard', 'How did you hear about us', 'LinkedIn', 'Common questions'],
    ['previously_worked', 'Worked at this company before?', 'No', 'Common questions'],
    ['gender', 'Gender', DECLINE, 'Voluntary (EEO)', 'These are optional on every form. The default declines.'],
    ['hispanic', 'Hispanic or Latino', DECLINE, 'Voluntary (EEO)'],
    ['race', 'Race / ethnicity', DECLINE, 'Voluntary (EEO)'],
    ['veteran', 'Veteran status', DECLINE, 'Voluntary (EEO)'],
    ['disability', 'Disability status', DECLINE, 'Voluntary (EEO)'],
  ];

  // Order matters: first match wins. Tested against the field's label text, lowercased.
  const RULES = [
    ['email', /e-?mail/],
    ['phone_country', /country (phone )?code|phone.*country|dialing code|phone code/],
    ['phone_ext', /extension/],
    ['phone', /phone|mobile|cell/],
    ['preferred_name', /preferred|nick ?name/],
    ['first_name', /first.?name|given.?name|forename/],
    ['last_name', /last.?name|family.?name|surname/],
    ['middle_name', /middle/],
    ['full_name', /^(your |full |legal )?name\b|full.?name/],
    ['linkedin', /linkedin/],
    ['github', /github/],
    ['website', /website|portfolio|personal (site|url|page)|blog/],
    ['address', /address( line)? ?1|street|^address$|mailing address|^address\b/],
    ['address2', /address( line)? ?2|apt|suite/],
    ['postal', /postal|zip/],
    ['city', /\bcity\b|\btown\b/],
    ['province_state', /province|\bstate\b|region/],
    ['country', /\bcountry\b|location.*country/],
    ['school', /school|university|college|institution/],
    ['degree', /\bdegree\b|level of education|education level/],
    ['major', /major|field of study|discipline|program of study|area of study|concentration/],
    ['gpa', /\bgpa\b|grade point|cumulative average/],
    ['grad', /graduat/],
    ['start_available', /start date|available to start|earliest (possible )?start|when can you start|availability/],
    ['sponsor', /sponsor/],
    ['work_auth', /authori[sz]ed|legally (eligible|able|permitted|entitled)|eligible to work|right to work|work permit|work visa/],
    ['relocate', /relocat/],
    ['over_18', /18 years|age of 18|at least 18|over 18/],
    ['how_heard', /how did you (hear|find|learn|come)|where did you (hear|find)|^source$|how .*learn about/],
    ['previously_worked', /previously (been )?(employed|worked)|former(ly)? (employee|employed)|worked (for|at|with) .{0,40}(before|previously|in the past)|current or former/],
    ['pronouns', /pronoun/],
    ['hispanic', /hispanic|latin[oax]/],
    ['gender', /gender|\bsex\b/],
    ['race', /\brace\b|ethnic/],
    ['veteran', /veteran|military|armed forces/],
    ['disability', /disabilit/],
  ];

  window.RM_FIELDS = { PROFILE, RULES, DECLINE };
})();
